### ISSUE TITLE
Electron 1.2

### ISSUE THREAD

**Issue by slyngbaek** [pirafrank/electron-dash-docset#2]
The script doesn't seem to work on the new Electron docs :(

**Comment by pirafrank** [comment]
Thank you for noticing. Working at it.

**Comment by pirafrank** [comment]
Waiting for PR from a guy who already fixed it.
Btw I've already made a PR to Dash User Docs repo with all missing electron versions.

**Comment by pirafrank** [comment]
[This](https://github.com/pirafrank/electron-dash-docset/commit/1f0ba9c9fb8f97061982698f177694e8dc4fd993) commit fixes the issue
